export const PAYMENT_CONFIG = {
  PAYSTACK_PUBLIC_KEY: process.env.EXPO_PUBLIC_PAYSTACK_KEY,
  FLUTTERWAVE_PUBLIC_KEY: process.env.EXPO_PUBLIC_FLUTTERWAVE_KEY,
  ENVIRONMENT: process.env.EXPO_PUBLIC_ENVIRONMENT || 'test'
};
